### ISSUE TITLE
Support Key_CapsLock

### ISSUE THREAD

**Issue by jjochen** [keyboardio/Kaleidoscope-LED-ActiveModColor#10]
`Key_CapsLock` should be highlighted with `sticky_color` when caps lock is activated.

**Comment by algernon** [comment]
This is reasonably easy to do, but depends on us being able to accurately track the capslock state (which, I believe, we don't do properly yet).

You can add the following bit of code to the plugin to test if it works (after the `Key k = Layer.lookupOnActiveLayer(r, c);` line)

```c++
if (k.raw == Key_CapsLock.raw) {
  if (kaleidoscope::hid::getKeyboardLEDs() & LED_CAPS_LOCK) {
    ::LEDControl.setCrgbAt(r, c, sticky_color);
  } else {
    ::LEDControl.refreshAt(r, c);
  }
}
```

Can you try if that works for you?

**Comment by jjochen** [comment]
It works fine the first time I switch on caps lock. But it doesn’t go out once I disable it.

**Comment by algernon** [comment]
Mhm, I figured that'd be the case. I need to fix capslock tracking first then, and then the above code will Just Work (and once I fixed caps tracking, I'll add those lines to the plugin).

**Comment by algernon** [comment]
This depends on keyboardio/Arduino-HID#3 being fixed first.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#402.
