### ISSUE TITLE
Colour not showing on NumLock

### ISSUE THREAD

**Issue by abhorrentPantheon** [keyboardio/Kaleidoscope-LED-ActiveModColor#12]
Couldn't find anything relating to this, and wouldn't be at all surprised if this is me making a mess of the sketch - apologies if so, and please let me know where I can find a fix.

ActiveModColor correctly lights up on normal (QWERTY) layer, however is not shown when NumLock is active. Turning NumLock off reinstates correct lighting. e.g. If LeftShift is sticky, turning NumLock on makes highlight turn off; NumLock off turns on highlight again.

**Comment by obra** [comment]
That's due to the design of the numpad plugin. The Numpad effect is
designed to block out all other LED behavior. I'd certainly be happy to
look at a proposed patch for Numpad to change that.

For now, I'm resolving this, since it's not specifically related to
activemodcolor.

Best,
Jesse
ᐧ
