### ISSUE TITLE
doesn't illuminate Fn / layer keys

### ISSUE THREAD

**Issue by ToyKeeper** [keyboardio/Kaleidoscope-LED-ActiveModColor#2]
This is a nice effect, particularly when combined with OneShot, but it doesn't light up the Fn keys while they have a different layer active.  It only seems to illuminate mod keys handled by the host OS.

Could we make it work with Fn keys too?

**Comment by algernon** [comment]
Yeah, can do that without much effort. It doesn't do that at the moment, because I wasn't considering layer keys as modifiers. And because there is no `isLayerKeyActive()` function, so detecting active layer keys is a little bit harder. But not too hard, so I'll give this a go.
