### ISSUE TITLE
Interaction with LED-Stalker

### ISSUE THREAD

**Issue by cdisselkoen** [keyboardio/Kaleidoscope-LED-ActiveModColor#4]
When both LED-Stalker and ActiveModColor are active, ActiveModColor 'highlights' may erroneously remain active after the key is released.

I'm reproducing this on a system affected by #3.

Steps to reproduce: 
1. Boot keyboard (both Stalker and ActiveModColor included in the sketch; Fn keys are mapped as in the default firmware)
2. Activate Stalker
3. Press/release left Fn.  Works correctly, except we observe the bug described in #3.
4. Press and hold right Fn.  Highlights both left and right Fn, as observed in #3.
5. Release right Fn.  Left Fn remains highlighted.

This only occurs under Stalker (well, at least, it doesn't occur under several other LED modes I had loaded).  Could be a problem with Stalker rather than ActiveModColor.  Curiously, the bug only occurs if you hold the key in step 4 long enough.  A quick tap will not trigger the bug.  Note that the Fn keys are not OneShots as I'm reproducing this, so it's unlikely OneShot timeouts are involved.

Also, it's a visual bug only; Fn keys continue to work normally although the highlighting is misleading.

**Comment by algernon** [comment]
I can't seem to be able to reproduce this (neither without, nor with the fix for #3) :|

Can you check if this is still reproducible with the latest master branch, with the fix for #3 applied?

**Comment by cdisselkoen** [comment]
Sorry for the long delay.  I can't reproduce this anymore either, so I'm going to assume it has been resolved.
