### ISSUE TITLE
In combination with some LED effects the modifiers do not turn off

### ISSUE THREAD

**Issue by domenzain** [keyboardio/Kaleidoscope-LED-ActiveModColor#8]
When combining ActiveModColor with StalkerEffect or AlphaSquareEffect, the modifiers stay white after pressing them once, even if they are not active.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#401.
